using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Dinheiro.RemoveUnnecessaryHeaders")]
[assembly: AssemblyDescriptionAttribute("Removes unnecessary ASP.NET MVC HTTP headers")]
[assembly: AssemblyCopyrightAttribute("Copyright David Duffett 2012")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0")]

