using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Dinheiro.GoogleAnalytics")]
[assembly: AssemblyDescriptionAttribute("ASP.NET MVC Helper Methods for Google Analytics")]
[assembly: AssemblyCopyrightAttribute("Copyright David Duffett 2014")]
[assembly: AssemblyVersionAttribute("2.0.4")]
[assembly: AssemblyFileVersionAttribute("2.0.4")]
[assembly: AssemblyInformationalVersionAttribute("2.0.4")]

