using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Dinheiro.GoogleAnalytics")]
[assembly: AssemblyDescriptionAttribute("ASP.NET MVC Helper Methods for Google Analytics")]
[assembly: AssemblyCopyrightAttribute("Copyright David Duffett 2013")]
[assembly: AssemblyVersionAttribute("1.1.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0")]

